### ISSUE TITLE
How do I use a video as an input instead of the camera

### ISSUE THREAD

**Issue by Altomand** [google-coral/example-object-tracker#26]
### Description

I changed the src path to a video saved on the Coral dev mini however I get this error even after converting the video to the required format
Traceback (most recent call last):
  File "detect11.py", line 404, in <module>
    main()
  File "detect11.py", line 400, in main
    videofmt=args.videofmt)
  File "/home/mendel/google-coral/example-object-tracker/gstreamer/gstreamer.py", line 275, in run_pipeline
    pipeline = GstPipeline(pipeline, user_function, src_size, mot_tracker)
  File "/home/mendel/google-coral/example-object-tracker/gstreamer/gstreamer.py", line 39, in __init__
    self.pipeline = Gst.parse_launch(pipeline)
gi.repository.GLib.Error: gst_parse_error: could not link videoscale0 to queue1, videoscale0 can't handle caps video/x-h264, width=(int)640, height=(int)480, framerate=(fraction)30/1 (3)

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Operating System

Mendel Linux

### Coral Device

Dev Board

### Programming Language

Python 3.7

### Relevant Log Output

```shell
Traceback (most recent call last):
  File "detect11.py", line 404, in <module>
    main()
  File "detect11.py", line 400, in main
    videofmt=args.videofmt)
  File "/home/mendel/google-coral/example-object-tracker/gstreamer/gstreamer.py", line 275, in run_pipeline
    pipeline = GstPipeline(pipeline, user_function, src_size, mot_tracker)
  File "/home/mendel/google-coral/example-object-tracker/gstreamer/gstreamer.py", line 39, in __init__
    self.pipeline = Gst.parse_launch(pipeline)
gi.repository.GLib.Error: gst_parse_error: could not link videoscale0 to queue1, videoscale0 can't handle caps video/x-h264, width=(int)640, height=(int)480, framerate=(fraction)30/1 (3)
```
</details>

**Comment by alkurop** [comment]
This issue also happened to me. Please check
